### ISSUE TITLE
Error: cannot find property SPLIT using browserify

### ISSUE THREAD

**Issue by inglesuniversal** [MrYakobo/video-thumbnail#2]
Hello:

I find your script very useful.

However, after bundling with browserify I got this error:

bundle.js:28107 Uncaught TypeError: Cannot read property 'split' of undefined

CODE where error pops up:

(function (process){
/*!
 * node-version
 * Copyright(c) 2011-2018 Rodolphe Stoclin
 * MIT Licensed
 */

module.exports = (function() {
  var version = process.versions.node;

  var split = version.split('.');

  return {
    original: 'v' + version,
    short: split[0] + '.' + split[1],
    long: version,
    major: split[0],
    minor: split[1],
    build: split[2]
  };
})();

**Comment by MrYakobo** [comment]
Hi, thank you for showing interest. This module is meant to be used with nodejs. This is because of the dependency of ffmpeg, et al. So browserify won't work, sadly.
